### ISSUE TITLE
implement changes

### ISSUE THREAD

**Issue by wuilmerj24** [marceloneppel/rethinkdb#11]
Hello, how can I implement changes and listen to each change?

**Comment by marceloneppel** [comment]
Hello Wuilmer!

Sorry for the delay!

Here is a link with an example of using changes do listen for each change: https://github.com/marceloneppel/rethinkdb/blob/c0e4426de74eef467fb905517cb4d6666060e81e/test/data_test.dart#L187

**Comment by marceloneppel** [comment]
Now i'm watching all issues in this repository.

**Comment by wuilmerj24** [comment]
@marceloneppel Hi thanks. 

How can I know if I connect to the db?
Because if it is not connected, the app remains blan

**Comment by MedoElkamaly** [comment]
Hi,

`Feed feed =
          await r.table(tableName).changes().run(connection).asStream()`
is not subscribing to the change feed, it only brings the values when called.
Is there is any solution?

Thanks

**Comment by pasanlive** [comment]
@marceloneppel I'm facing the same issue mentioned above. Seems it is not subscribing to the change feed, it only brings the values when called.

Thank you

**Comment by marceloneppel** [comment]
@MedoElkamaly and @pasanlive, could you try the example on https://github.com/marceloneppel/rethinkdb_example?

It's working with changes. Do you have some code to show the problem?

**Comment by pasanlive** [comment]
@marceloneppel It worked. Thank you very much

**Comment by malikdoksoz** [comment]
Can i listen to live data with future or stream builder?
 I dont want to use

```dart
  feed.listen((data) {
    print('feed data: $data');
  });
```
